variables:
  ARM_PASS: $(adminPass)

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'quickstarts/microsoft.web/webapp-linux-managed-mysql'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Pass - Sponsorship-13July(90005c67-7555-493b-ba11-a38de0084ce6)'
    subscriptionId: '90005c67-7555-493b-ba11-a38de0084ce6'
    action: 'DeleteRG'
    resourceGroupName: 'AzARMTemplateDeployment'
    location: 'East US'
